### ISSUE TITLE
Rendering issues on ftthread branch with Chromium/Chrome

### ISSUE THREAD

**Issue by 3v1n0** [behdad/freetype#1]
Hi, I''ve been trying your multi-threading safe branch both backporting it to 2.5.2 (as it's used by ubuntu trusty) and both using the git version, but I'm getting some rendering issues in Chromium.

This is what I'm getting (git version):
![chrome-issue](https://cloud.githubusercontent.com/assets/345675/5891439/10abcd8c-a496-11e4-8665-534013c33d1d.png)

(2.5.2 + your patches):
![chrome fonts](https://cloud.githubusercontent.com/assets/345675/5891437/ef47ef2c-a495-11e4-9247-2cb3543020e2.png)

PS: do you want me to open a bug in upstream freetype as this is now there?

**Comment by behdad** [comment]
That was fixed yesterday:
https://github.com/behdad/freetype/commit/264b5e46c0d166c11360eb6c29edf2c178bb87c7

These are all upstream now BTW.

**Comment by 3v1n0** [comment]
Great, thanks!
